<table>
    <thead>
        <tr>
            <th>Coin</th>
            <th>Price</th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td>BTC</td>
            <td>$38,789.03</td>
        </tr>
        <tr>
            <td>ETH</td>
            <td>$2,846.29</td>
        </tr>
        <tr>
            <td>USDT</td>
            <td>$1.00</td>
        </tr>
        <tr>
            <td>BNB</td>
            <td>$387.51</td>
        </tr>
        <tr>
            <td>USDC</td>
            <td>$1.00</td>
        </tr>
        <tr>
            <td>SOL</td>
            <td>$97.69</td>
        </tr>
        <tr>
            <td>XRP</td>
            <td>$0.6462</td>
        </tr>
        <tr>
            <td>LUNA</td>
            <td>$88.57</td>
        </tr>
        <tr>
            <td>ADA</td>
            <td>$0.8358</td>
        </tr>
        <tr>
            <td>AVAX</td>
            <td>$70.39</td>
        </tr>
    </tbody>
</table>